#!/bin/zsh
autoload zmv
alias mmv='noglob zmv -W'

alias su='export XAUTHORITY=${HOME}/.Xauthority ; sudo -s'
alias sudo='export XAUTHORITY=${HOME}/.Xauthority ; sudo'

alias du="du -hcs"
alias df="df -h"

EXC="--hide='*.py[co]'"
case "${$(ls --version | head -1)##* }" in
    [0-5].*)
        alias ls="ls -bCF --color=auto $EXC"
        ;;
    *)
        alias ls="ls --group-directories-first -bCF --color=auto $EXC" 
        ;;
esac

alias la="ls --color=always -a"
alias ll="ls --color=always -l $EXC"
alias lla="ls --color=always -la"
alias lal="ls --color=always -la"

alias egrep='egrep --color=tty -d skip'
alias fgrep='fgrep --color=tty -d skip'
alias grep='grep --color=tty -d skip'

alias md='mkdir'
alias rd='rmdir'
alias rm='rm -i'

#conf_push () {
#    echo -n "PUSHING TO $1"
#    rsync -au --exclude=.git --delete ~madcoder/.madconf/ "$1":.madconf/
#    ssh "$1" LC_ALL=C .madconf/bin/madconf
#    echo "."
#}

alias servedir='python -c "import SimpleHTTPServer;SimpleHTTPServer.test()"'
alias servedircgi='python -c "import CGIHTTPServer;CGIHTTPServer.test()"'
#alias xrunserver='xterm -T "runserver `basename $PWD`" -e "cd $PWD; ./manage.py runserver 0.0.0.0:8000; sleep 2 "'
