#! /bin/zsh

autoload colors && colors
autoload -Uz vcs_info

precmd() {
    title "zsh" "$USER@%m" "%55<...<%~"

    psvar=()
    vcs_info
    if [ "${vcs_info_msg_0_}" != "" ]; then
      psvar[1]="${vcs_info_msg_0_}"
    fi
}

_mad_prompt_setup() {
    local rst
    local -a pcc

    rst="%{$reset_color%}"
    pcc[1]="%{$reset_color${1:-$fg_no_bold[green]}%}"
    pcc[2]="%{$reset_color${2:-$fg_no_bold[yellow]}%}"
    pcc[3]="%{$reset_color${3:-$fg_no_bold[cyan]}%}"
    pcc[4]="%{$reset_color${4:-$fg_bold[red]}%}"

#%{$'\e[s\e[A\e[4Dblah\e[u'$reset_color%}
#%{$'\e[400C\e[20D'%}"────────────────────
    PROMPT="\
$pcc[1]┌─(%B%T$pcc[1])──%(1v.<$pcc[3]%1v %B%U%2v%u%(3v.$pcc[4] <%3v>.)$pcc[1]>.)──
$pcc[1]└[$pcc[2]%{%(?..%S)%}%m%s$pcc[1]] $rst"
    RPROMPT="$pcc[1](%B%~$pcc[1])$rst"
    POSTEDIT=$reset_color
}

if [ $UID -eq 0 ]; then
    PATH=~root/bin:/usr/local/sbin:/usr/sbin:/sbin:$PATH
    PROMPT="%{$reset_color$fg_bold[yellow]%}[%{$fg_bold[red]%}%n %m%{$fg_bold[yellow]%}]%{$reset_color%} "
    RPROMPT="%{$reset_color$fg_no_bold[red]%}(%{$fg_bold[red]%}%~%{$fg_no_bold[red]%})%{$reset_color%} "
else
    PATH="/usr/lib/ccache:${HOME}/bin:${HOME}/.madconf/bin:${PATH}"
    _mad_prompt_setup
fi

# format titles for screen and rxvt
function title() {
  # escape '%' chars in $1, make nonprintables visible
  a=${(V)1//\%/\%\%}

  # Truncate command, and join lines.
  a=$(print -Pn "%40>...>$a" | tr -d "\n")

  case $TERM in
  screen)
    print -Pn "\ek$a:$3\e\\"      # screen title (in ^A")
    ;;
  xterm*|rxvt)
    print -Pn "\e]2;$2 | $a:$3\a" # plain xterm title
    ;;
  esac
}

preexec () {
    #PROMPT="${PROMPT}%{kzsh\\%}"
    #local CMD=${1[(wr)^(*=*|sudo|exec|-*)]}
    #echo -ne "\ek$CMD\e\\"
    title "$1" "$USER@%m" "%35<...<%~"
}
